#!/bin/bash
echo "hello"
CURRENT_ENV=DEV

if [ -z ${CURRENT_ENV+x} ]; then
     echo "CURRENT_ENV is not defined";
else
    if [ $CURRENT_ENV = "PROD" ]; then
        echo "Loading PROD configuration"
        TEST_ENV="Below are the Prod123 ${CURRENT_ENV}environment variables"

    elif [ $CURRENT_ENV = "UAT" ]; then
        echo "Loading UAT configuration"
        TEST_ENV="Below are the Prod123 ${CURRENT_ENV}environment variables"
    else
        echo "Loading Dev configuration"
        TEST_ENV="Below are the Prod123 ${CURRENT_ENV}environment variables"

    fi
fi